import type { Lead } from "./types"

// Mock data for leads
export const mockLeads: Lead[] = [
  {
    id: "1",
    firstName: "Jorge",
    lastName: "Ruiz",
    email: "jorge.ruiz@example.com",
    linkedInProfile: "linkedin.com/in/jorgeruiz",
    visasOfInterest: ["O-1"],
    additionalInfo: "Looking for opportunities in tech industry",
    status: "PENDING",
    createdAt: "02/02/2024, 2:45 PM",
    country: "Mexico",
  },
  {
    id: "2",
    firstName: "Bahar",
    lastName: "Zamir",
    email: "bahar.zamir@example.com",
    linkedInProfile: "linkedin.com/in/baharzamir",
    visasOfInterest: ["EB-1A", "O-1"],
    resumeUrl: "/resumes/baharzamir.pdf",
    status: "PENDING",
    createdAt: "02/02/2024, 2:45 PM",
    country: "Mexico",
  },
  {
    id: "3",
    firstName: "Mary",
    lastName: "Lopez",
    email: "mary.lopez@example.com",
    linkedInProfile: "linkedin.com/in/marylopez",
    visasOfInterest: ["EB-2 NIW"],
    additionalInfo: "PhD in Biomedical Engineering",
    status: "PENDING",
    createdAt: "02/02/2024, 2:45 PM",
    country: "Brazil",
  },
  {
    id: "4",
    firstName: "Li",
    lastName: "Zijin",
    email: "li.zijin@example.com",
    linkedInProfile: "linkedin.com/in/lizijin",
    visasOfInterest: ["O-1", "EB-1A"],
    resumeUrl: "/resumes/lizijin.pdf",
    status: "PENDING",
    createdAt: "02/02/2024, 2:45 PM",
    country: "South Korea",
  },
  {
    id: "5",
    firstName: "Mark",
    lastName: "Antonov",
    email: "mark.antonov@example.com",
    linkedInProfile: "linkedin.com/in/markantonov",
    visasOfInterest: ["EB-2 NIW"],
    additionalInfo: "Software Engineer with 10 years of experience",
    status: "PENDING",
    createdAt: "02/02/2024, 2:45 PM",
    country: "Russia",
  },
  {
    id: "6",
    firstName: "Jane",
    lastName: "Ma",
    email: "jane.ma@example.com",
    linkedInProfile: "linkedin.com/in/janema",
    visasOfInterest: ["I don't know"],
    additionalInfo: "Looking for consultation on visa options",
    status: "PENDING",
    createdAt: "02/02/2024, 2:45 PM",
    country: "Mexico",
  },
  {
    id: "7",
    firstName: "Anand",
    lastName: "Jain",
    email: "anand.jain@example.com",
    linkedInProfile: "linkedin.com/in/anandjain",
    visasOfInterest: ["O-1"],
    resumeUrl: "/resumes/anandjain.pdf",
    status: "REACHED_OUT",
    createdAt: "02/02/2024, 2:45 PM",
    country: "Mexico",
  },
  {
    id: "8",
    firstName: "Anna",
    lastName: "Voronova",
    email: "anna.voronova@example.com",
    linkedInProfile: "linkedin.com/in/annavoronova",
    visasOfInterest: ["EB-1A", "EB-2 NIW"],
    additionalInfo: "Researcher in AI and Machine Learning",
    status: "PENDING",
    createdAt: "02/02/2024, 2:45 PM",
    country: "France",
  },
]

